#!/bin/bash

# Define simple calculators
max_intel_brightness=$( cat /sys/class/backlight/intel_backlight/max_brightness )
calc(){ awk "BEGIN { print "$*" }"; }
calc_intel_to_percentage(){ calc $1/$max_intel_brightness*100 ; }
calc_percentage_to_intel(){ calc $1*$max_intel_brightness/100 ; }
float_to_int(){  printf "%.0f\n" "$@" ; }

# Determine whether we can do the change
current_intel_brightness=$( cat /sys/class/backlight/intel_backlight/brightness )
min_percentage_brightness=10
max_percentage_brightness=95
change_percentage_brightness=$1 # User input
current_percentage_brightness=$( calc_intel_to_percentage $current_intel_brightness  )
final_float_percentage_brightness=$( calc $current_percentage_brightness+$change_percentage_brightness   )
final_percentage_brightness=$( float_to_int $final_float_percentage_brightness )
if [ $final_percentage_brightness -le $min_percentage_brightness -o $max_percentage_brightness -le $final_percentage_brightness ]; then
    exit 0  # Exit with success code
fi

# If change can be done:
# 1. Do it in the laptop
final_float_intel_brightness=$( calc_percentage_to_intel $final_percentage_brightness )
final_intel_brightness=$( float_to_int $final_float_intel_brightness )
echo $final_intel_brightness | tee /sys/class/backlight/intel_backlight/brightness
# 2. Do it in external screen (if connected)
external_screen=$( xrandr -q | grep -v "eDP-1" | grep -v "disconnected" | grep "connected" | awk '{print $1}' )
final_fraction_brightness=$( calc $final_percentage_brightness/100 )
xrandr --output $external_screen --brightness $final_fraction_brightness
